version: "3"
services:
  app:
    build: .
    ports:
      - 4000:4000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/test
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.12
    ports:
      - 27017:27017
